-- Constants.lua
-- Central tuning values and compatibility constants for BossTracker.

local addon = _G.BossTracker
local C = {}
addon.Core.Constants = C

C.VERSION = "1.13.12"
C.SCHEMA_VERSION = 7
C.INTERPRETATION_ENGINE_VERSION = 21
C.LEARNED_BACKUP_SCHEMA_VERSION = 2
C.EVIDENCE_SCHEMA_VERSION = 2
C.EVIDENCE_COMPLETION_REASONS = {
	unit_died = true,
	low_hp_completion = true,
}

C.DEFAULT_CONFIG = {
	enabled = true,
	timersEnabled = true,
	debugEnabled = false,
	uiLocked = false,
	maxBars = 8,
	minTimerDisplayInterval = 10,
	warningLeadTime = 3,
	minTimerConfidence = 0.25,
	minEncounterConfidence = 0.55,
	minTimerSeconds = 1.0,
	combatLogDebug = false,
	overrides = {
		zones = {},
	},
}

C.DEFAULT_CHAR_CONFIG = {
	ui = {
		point = "CENTER",
		relativePoint = "CENTER",
		x = 0,
		y = 180,
		width = 340,
		height = 248,
		scale = 1.0,
	},
	minimap = {
		angle = 225,
	},
	panic = false,
	previewTimers = false,
}

C.WARNING_SOUND_OFF = "none"
C.WARNING_SOUND_OPTIONS = {
	{
		key = C.WARNING_SOUND_OFF,
		label = "None",
		shortLabel = "None",
	},
	{
		key = "soft_bell",
		label = "Soft Bell",
		shortLabel = "Bell",
		path = "Sound\\Doodad\\BellTollNightElf.wav",
	},
	{
		key = "flag_alert",
		label = "Flag Alert",
		shortLabel = "Flag",
		path = "Sound\\Spells\\PVPFlagTaken.wav",
	},
	{
		key = "warning_chime",
		label = "Warning Chime",
		shortLabel = "Warn",
		path = "Sound\\Spells\\PVPWarning.wav",
	},
	{
		key = "focus_chime",
		label = "Focus Chime",
		shortLabel = "Chime",
		path = "Interface\\AddOns\\BossTracker\\Media\\Sounds\\bt_focus_chime.wav",
	},
	{
		key = "soft_pulse",
		label = "Soft Pulse",
		shortLabel = "Pulse",
		path = "Interface\\AddOns\\BossTracker\\Media\\Sounds\\bt_soft_pulse.wav",
	},
	{
		key = "glass_tick",
		label = "Glass Tick",
		shortLabel = "Tick",
		path = "Interface\\AddOns\\BossTracker\\Media\\Sounds\\bt_glass_tick.wav",
	},
	{
		key = "rising_sweep",
		label = "Rising Sweep",
		shortLabel = "Sweep",
		path = "Interface\\AddOns\\BossTracker\\Media\\Sounds\\bt_rising_sweep.wav",
	},
}

C.MAX_DEBUG_RUNS = 2
C.MAX_DEBUG_LOGS = 120
C.MAX_DEBUG_ERRORS = 40
C.MAX_DEBUG_EVENTS_PER_RUN = 600
C.MAX_DEBUG_PULLS_PER_RUN = 30
C.MAX_DEBUG_CONTEXTS_PER_RUN = 120
C.MAX_PULL_EVENTS = 120
C.MAX_PULL_HP_SAMPLES = 80
C.MAX_PULL_SPELLS = 220
C.MAX_PULL_CANDIDATES = 80
C.MAX_PULL_BOSS_CONTEXTS = 80
C.MAX_LEARNED_ZONES = 120
C.MAX_LEARNED_BOSSES_PER_ZONE = 80
C.MAX_LEARNED_ABILITIES_PER_BOSS = 180
C.MAX_LEARNED_ENCOUNTERS_PER_ZONE = 80
C.MAX_LEARNED_ACTORS_PER_ENCOUNTER = 12
C.MAX_EVIDENCE_INSTANCES = 80
C.MAX_EVIDENCE_BOSSES_PER_INSTANCE = 100
C.MAX_EVIDENCE_KILLS_PER_BOSS = 30
C.MAX_EVIDENCE_ACTORS_PER_KILL = 64
C.MAX_EVIDENCE_SPELLS_PER_KILL = 220
C.MAX_EVIDENCE_EVENTS_PER_KILL = 2400
C.MAX_EVIDENCE_DRAFT_ACTORS = 256
C.MAX_EVIDENCE_DRAFT_SPELLS = 440
C.MAX_EVIDENCE_HP_SAMPLES_PER_ACTOR = 80
C.MAX_EVIDENCE_INCOMPLETE_ATTEMPTS = 80
C.MAX_EVIDENCE_ARCHIVES = 3
C.SYNC_PREFIX = "BT_SYNC1"
C.SYNC_TRANSPORT_PREFIX = "BT_TRN1"
C.PULL_TIMER_PREFIX = "BT_PULL1"
C.PULL_TIMER_DEFAULT_SECONDS = 10
C.PULL_TIMER_MAX_SECONDS = 300
C.SYNC_CHUNK_BYTES = 190
C.SYNC_SEND_INTERVAL_SECONDS = 0.10
C.SYNC_MAX_PARALLEL_MESSAGES_PER_TICK = 8
C.SYNC_REQUEST_TIMEOUT_SECONDS = 60
C.SYNC_TRANSFER_TIMEOUT_SECONDS = 300
C.SYNC_TRANSPORT_ACCEPT_WINDOW_SECONDS = 6
C.SYNC_TRANSPORT_MANIFEST_NO_PROGRESS_SECONDS = 8
C.SYNC_TRANSPORT_MANIFEST_MAX_SECONDS = 20
C.SYNC_TRANSPORT_PLAN_ACK_TIMEOUT_SECONDS = 5
C.SYNC_TRANSPORT_GROUP_NO_PROGRESS_SECONDS = 20
C.SYNC_TRANSPORT_STALE_TIMEOUT_SECONDS = 900
C.SYNC_TRANSPORT_CHUNK_BYTES = 170
C.SYNC_TRANSPORT_MIN_CHUNKS_PER_SECOND = 1
C.SYNC_TRANSPORT_START_CHUNKS_PER_SECOND = 4
C.SYNC_TRANSPORT_MAX_CHUNKS_PER_SECOND = 40
C.SYNC_TRANSPORT_MAX_CHUNK_CREDIT = 12
C.SYNC_TRANSPORT_MAX_ACTIVE_PROVIDERS = 3
C.SYNC_TRANSPORT_FLOW_WINDOW_CHUNKS = 64
C.SYNC_TRANSPORT_FLOW_MIN_INTERVAL_SECONDS = 4
C.SYNC_TRANSPORT_MAX_ITEMS_PER_GROUP = 40
C.MAX_SYNC_KILLS_PER_PAYLOAD = 80
C.MAX_SYNC_KILLS_PER_EXPORT = C.MAX_SYNC_KILLS_PER_PAYLOAD
C.MAX_SYNC_PAYLOAD_BYTES = 180000
C.MAX_SYNC_CHUNKS = 1000

C.EVENT_DEDUPE_SECONDS = 1.5
C.CAST_RESOLUTION_DEDUPE_SECONDS = 12.0
C.AURA_LIFECYCLE_DEDUPE_SECONDS = 20.0
C.PLAYER_AURA_REAPPLY_DEDUPE_SECONDS = 12.0
C.PLAYER_AURA_LIFECYCLE_DEDUPE_SECONDS = 20.0
C.MIN_INTERVAL_SECONDS = 3.0
C.MIN_TIMER_DISPLAY_INTERVAL_SECONDS = 10.0
C.CAST_TIMER_DISPLAY_FLOOR_GRACE_SECONDS = 0.5
C.UNSTABLE_TIMER_INTERVAL_RATIO = 3.0
C.UNSTABLE_TIMER_INTERVAL_SPREAD_SECONDS = 30.0
C.PHASE_TIMER_INTERVAL_RATIO = 1.8
C.PHASE_TIMER_INTERVAL_SPREAD_SECONDS = 8.0
C.TERMINAL_CAST_MAX_HP_PCT = 5.0
C.TERMINAL_CAST_MIN_OFFSET_SECONDS = 120.0
C.GLOBAL_ROUTINE_SPELL_MIN_ENCOUNTERS = 10
C.MAX_REASONABLE_INTERVAL_SECONDS = 300.0
C.MIN_HP_GATE_SAMPLES = 3
C.MIN_PHASE_RULE_SAMPLES = 2
C.HP_TRANSITION_AURA_TARGET_PCT = 50.0
C.HP_TRANSITION_AURA_TOLERANCE_PCT = 3.0
C.PHASE_GAP_SECONDS = 35.0
C.ENCOUNTER_GROUP_GAP_SECONDS = 18.0
C.ENCOUNTER_CONTAINED_ADD_START_GRACE_SECONDS = 2.0
C.ENCOUNTER_CONTAINED_ADD_MAX_EVENTS = 30
C.ENCOUNTER_CONTAINED_ADD_MAX_OCCURRENCES = 24
C.ENCOUNTER_CONTAINED_ADD_MAX_ABILITIES = 3
C.HP_GATE_SPREAD_PCT = 7.0
C.PHASE_HP_BUCKETS = { 90, 80, 75, 70, 65, 60, 50, 40, 35, 30, 25, 20, 15, 10 }
C.TIMER_UPDATE_SECONDS = 0.15
C.TIMER_DELAYED_VISIBLE_SECONDS = 8.0
C.ENCOUNTER_TICK_SECONDS = 0.50
C.MAX_BOSS_UNIT_FRAMES = _G.MAX_BOSS_FRAMES or 5
C.COMBAT_END_SETTLE_SECONDS = 2.0
C.BOSS_DEATH_VISUAL_GRACE_SECONDS = 2.5
C.BOSS_OUT_OF_COMBAT_HOLD_SECONDS = 10.0
C.BOSS_CONTEXT_IDLE_SECONDS = 75.0
C.MODULE_ERROR_LIMIT = 5

C.BOSS_CONTEXT_MIN_CONFIDENCE = 0.55
C.FALLBACK_BOSS_CONTEXT_MIN_CONFIDENCE = 0.85
C.FALLBACK_RAREELITE_CONTEXT_MIN_CONFIDENCE = 0.75
C.BOSS_FRAME_ADD_CONTEXT_MIN_CONFIDENCE = 0.95
C.BOSS_COMPLETION_HP_THRESHOLD = 5.0

C.EVENT_IMPORTANCE = {
	SPELL_CAST_START = 5,
	SPELL_CAST_SUCCESS = 5,
	SPELL_AURA_APPLIED = 3,
	SPELL_AURA_REFRESH = 2,
	SPELL_DAMAGE = 2,
	SPELL_MISSED = 2,
	SPELL_HEAL = 3,
	SPELL_INTERRUPT = 4,
	SPELL_SUMMON = 4,
	RANGE_DAMAGE = 2,
	RANGE_MISSED = 2,
	UNIT_DIED = 3,
}

C.PRIMARY_OCCURRENCE_EVENTS = {
	SPELL_CAST_START = true,
	SPELL_CAST_SUCCESS = true,
	SPELL_AURA_APPLIED = true,
	SPELL_AURA_REFRESH = true,
	SPELL_DAMAGE = true,
	SPELL_MISSED = true,
	SPELL_HEAL = true,
	SPELL_INTERRUPT = true,
	SPELL_SUMMON = true,
	RANGE_DAMAGE = true,
	RANGE_MISSED = true,
}

C.PERIODIC_EVENTS = {
	SPELL_PERIODIC_DAMAGE = true,
	SPELL_PERIODIC_MISSED = true,
	SPELL_PERIODIC_HEAL = true,
	SPELL_PERIODIC_AURA_APPLIED = true,
	SPELL_PERIODIC_AURA_REMOVED = true,
	SPELL_PERIODIC_ENERGIZE = true,
	SPELL_PERIODIC_DRAIN = true,
	SPELL_PERIODIC_LEECH = true,
}

C.FLAG_HOSTILE = _G.COMBATLOG_OBJECT_REACTION_HOSTILE or 0x00000040
C.FLAG_NPC = _G.COMBATLOG_OBJECT_TYPE_NPC or 0x00000800
C.FLAG_GUARDIAN = _G.COMBATLOG_OBJECT_TYPE_GUARDIAN or 0x00002000
C.FLAG_PET = _G.COMBATLOG_OBJECT_TYPE_PET or 0x00001000
C.FLAG_PLAYER = _G.COMBATLOG_OBJECT_TYPE_PLAYER or 0x00000400
C.FLAG_CONTROL_NPC = _G.COMBATLOG_OBJECT_CONTROL_NPC or 0x00000200
