-- Constants.lua
-- Central tuning values and compatibility constants for BossTracker.

local addon = _G.BossTracker
local C = {}
addon.Core.Constants = C

C.VERSION = "0.4.0"
C.SCHEMA_VERSION = 6

C.DEFAULT_CONFIG = {
	enabled = true,
	timersEnabled = true,
	debugEnabled = true,
	uiLocked = false,
	maxBars = 8,
	minTimerConfidence = 0.25,
	minEncounterConfidence = 0.55,
	minTimerSeconds = 1.0,
	combatLogDebug = true,
}

C.DEFAULT_CHAR_CONFIG = {
	ui = {
		point = "CENTER",
		relativePoint = "CENTER",
		x = 0,
		y = 180,
		width = 300,
		height = 194,
		scale = 1.0,
	},
	panic = false,
	previewTimers = false,
}

C.MAX_DEBUG_RUNS = 5
C.MAX_DEBUG_LOGS = 500
C.MAX_DEBUG_ERRORS = 120
C.MAX_DEBUG_EVENTS_PER_RUN = 2600
C.MAX_DEBUG_PULLS_PER_RUN = 80
C.MAX_DEBUG_CONTEXTS_PER_RUN = 240
C.MAX_PULL_EVENTS = 300
C.MAX_PULL_HP_SAMPLES = 160
C.MAX_PULL_SPELLS = 220
C.MAX_PULL_CANDIDATES = 80
C.MAX_PULL_BOSS_CONTEXTS = 80
C.MAX_LEARNED_ZONES = 120
C.MAX_LEARNED_BOSSES_PER_ZONE = 80
C.MAX_LEARNED_ABILITIES_PER_BOSS = 180
C.MAX_LEARNED_ENCOUNTERS_PER_ZONE = 80
C.MAX_LEARNED_ACTORS_PER_ENCOUNTER = 12

C.EVENT_DEDUPE_SECONDS = 1.5
C.CAST_RESOLUTION_DEDUPE_SECONDS = 8.0
C.AURA_LIFECYCLE_DEDUPE_SECONDS = 20.0
C.MIN_INTERVAL_SECONDS = 3.0
C.MIN_TIMER_DISPLAY_INTERVAL_SECONDS = 10.0
C.MAX_REASONABLE_INTERVAL_SECONDS = 300.0
C.MIN_HP_GATE_SAMPLES = 3
C.PHASE_GAP_SECONDS = 35.0
C.ENCOUNTER_GROUP_GAP_SECONDS = 18.0
C.HP_GATE_SPREAD_PCT = 7.0
C.PHASE_HP_BUCKETS = { 90, 80, 75, 70, 65, 60, 50, 40, 35, 30, 25, 20, 15, 10 }
C.TIMER_UPDATE_SECONDS = 0.15
C.ENCOUNTER_TICK_SECONDS = 0.50
C.MAX_BOSS_UNIT_FRAMES = _G.MAX_BOSS_FRAMES or 5
C.COMBAT_END_SETTLE_SECONDS = 2.0
C.BOSS_CONTEXT_IDLE_SECONDS = 75.0
C.MODULE_ERROR_LIMIT = 5

C.BOSS_CONTEXT_MIN_CONFIDENCE = 0.55
C.FALLBACK_BOSS_CONTEXT_MIN_CONFIDENCE = 0.85
C.FALLBACK_RAREELITE_CONTEXT_MIN_CONFIDENCE = 0.75
C.BOSS_FRAME_ADD_CONTEXT_MIN_CONFIDENCE = 0.95
C.BOSS_COMPLETION_HP_THRESHOLD = 5.0

C.EVENT_IMPORTANCE = {
	SPELL_CAST_START = 5,
	SPELL_CAST_SUCCESS = 5,
	SPELL_AURA_APPLIED = 3,
	SPELL_AURA_REFRESH = 2,
	SPELL_DAMAGE = 2,
	SPELL_MISSED = 2,
	SPELL_INTERRUPT = 4,
	SPELL_SUMMON = 4,
	RANGE_DAMAGE = 2,
	RANGE_MISSED = 2,
	UNIT_DIED = 3,
}

C.PRIMARY_OCCURRENCE_EVENTS = {
	SPELL_CAST_START = true,
	SPELL_CAST_SUCCESS = true,
	SPELL_AURA_APPLIED = true,
	SPELL_AURA_REFRESH = true,
	SPELL_DAMAGE = true,
	SPELL_MISSED = true,
	SPELL_INTERRUPT = true,
	SPELL_SUMMON = true,
	RANGE_DAMAGE = true,
	RANGE_MISSED = true,
}

C.PERIODIC_EVENTS = {
	SPELL_PERIODIC_DAMAGE = true,
	SPELL_PERIODIC_MISSED = true,
	SPELL_PERIODIC_HEAL = true,
	SPELL_PERIODIC_AURA_APPLIED = true,
	SPELL_PERIODIC_AURA_REMOVED = true,
	SPELL_PERIODIC_ENERGIZE = true,
	SPELL_PERIODIC_DRAIN = true,
	SPELL_PERIODIC_LEECH = true,
}

C.FLAG_HOSTILE = _G.COMBATLOG_OBJECT_REACTION_HOSTILE or 0x00000040
C.FLAG_NPC = _G.COMBATLOG_OBJECT_TYPE_NPC or 0x00000800
C.FLAG_GUARDIAN = _G.COMBATLOG_OBJECT_TYPE_GUARDIAN or 0x00002000
C.FLAG_PET = _G.COMBATLOG_OBJECT_TYPE_PET or 0x00001000
C.FLAG_PLAYER = _G.COMBATLOG_OBJECT_TYPE_PLAYER or 0x00000400
C.FLAG_CONTROL_NPC = _G.COMBATLOG_OBJECT_CONTROL_NPC or 0x00000200
